version: "3"

name: pg
services:
  database:
    image: "postgres"
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sustainability
    volumes:
      - ../1brc/:/1brc/:ro,Z 
